# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: scripts for setting up pi
    cmds:
      - ls
  install:
    cmds:
      - ./apk-setup-install.sh
      - ./fail2ban-install.sh
      - ./log2ram-install.sh
      - ./setup-unattended-upgrades.sh
